### PR TITLE
Make changes to cpp code to make python 3.7 compilation work.

### PR DESCRIPTION
**Pull request by cjordan**
Hi,

The master branch `cygrid` does not build on python 3.7, presumably because the C API has changed.  With a little work, I got `cygrid` to compile with this commit. It should be noted that I don't really know what I'm doing, and that this commit probably breaks building on versions <3.7, so I'm only providing this pull request just in case it makes someone else's life easier.  Feel free to reject it.

Schöne Grüße!

### CODE REVIEW

**Comment by bwinkel** [comment]
Hi @cjordan,

thanks a lot for this PR (my first!) and for the efforts you put in. It seems, that the changes do not work with Linux on Python 2.7/3.5/3.6 (see travis link above). How did you come up with the changes? Did you auto-generate these with cython? The way I'm usually doing this is to delete all cpp files and have the setup.py script do the rest.

**Comment by cjordan** [comment]
Hi @bwinkel,

In short, when I run `pip install .` in a `cygrid` repo checked out on the master branch, I get a lot of messages like the following:

>     cygrid/kernels.cpp:18588:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
>          tstate->exc_type = *type;
>                  ^~~~~~~~
>                  curexc_type
>     cygrid/kernels.cpp:18589:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
>          tstate->exc_value = *value;
>                  ^~~~~~~~~
>                  curexc_value
>     cygrid/kernels.cpp:18590:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
>          tstate->exc_traceback = *tb;
>                  ^~~~~~~~~~~~~
>                  curexc_traceback
>     cygrid/kernels.cpp: In function ‘PyObject* __Pyx_PyCFunction_FastCall(PyObject*, PyObject**, Py_ssize_t)’:
>     cygrid/kernels.cpp:18816:69: error: too many arguments to function
>          return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
>                                                                          ^
>     cygrid/kernels.cpp:18806:15: warning: unused variable ‘result’ [-Wunused-variable]
>          PyObject *result;
>                    ^~~~~~
>     cygrid/kernels.cpp:18807:9: warning: unused variable ‘flags’ [-Wunused-variable]
>          int flags;
>              ^~~~~
>     error: command 'gcc' failed with exit status 1

For reference, I'm running Archlinux, with its system python (3.7) and all other dependencies are up to date.

The pull request I've sent was created by some basic usage of `sed` to substitute e.g. `exc_type` for `curexc_type`.  There were also one or two places where I had to change the number of arguments called (remove a NULL, or change an argument to NULL).  It would make sense, however, that these .cpp files are somehow being automatically generated, because they're tens of thousands of lines long.  If they are being automatically generated, then I've gone about this the hard way :)

I'm not surprised that my pull request doesn't work on older versions of python, as 3.7 seems to have a new underlying API.  I don't know if there's an elegant way to make `cygrid` install on new and old versions of python simultaneously, but presumably many other projects have done this already.

**Comment by bwinkel** [comment]
Thanks for the additional information. Indeed, the cpp files are auto-generated by the cython (pre-)compiler and I just did this with the latest cython version. Seems to work on all python versions. I'll create a binary wheel later but installation from source should already work for you. Can you confirm?

**Comment by cjordan** [comment]
Sorry for the delay, timezones are a pain...

Yes, I confirm that removing the cpp files before building on python 3.7 allows the build to complete.  So I guess this pull request is entirely unnecessary and can be removed.

But while we're discussing this - if the cpp files are generated automatically, is there a point to including them in the source code?  If not, then maybe it would be worth removing them.

**Comment by bwinkel** [comment]
Shipping the cpp-files with the package, has the advantage that the user doesn't need Cython installed, but comes with the drawback that the package maintainer has to make sure to provide up-to-date versions of the files (I failed to do that, obviously). From what I've seen what other packages (that use Cython) do, most of them ship the cpp-files and don't rely on the users having Cython installed.

I'll close this PR for now, but want to thank you again for your help!

**Comment by bwinkel** [comment]
Closing as issue was fixed in ee47ec94ce2f1160cc1b36e1085ac37e0b5d2a13.
